import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, readFileSync, writeFileSync, existsSync, symlinkSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import { parse, stringify } from 'yaml';
import { services, packageRoot } from '../dist/bootstrap.js';
import { initialize } from '../dist/infrastructure/scaffold/init.js';
import { migrateLegacy } from '../dist/infrastructure/legacy/migrate.js';
import { init as legacyInit, loadProduct } from '../dist/legacy/v0/index.js';
import { analyzeDecision, evaluateDecision } from '../dist/domain/decisions.js';
import { graph } from '../dist/domain/graph.js';
const cli=resolve('dist/interfaces/cli/main.js');
function fixture(t, language='pt') { const root=mkdtempSync(join(tmpdir(),'intent-test-')); t.after(()=>rmSync(root,{recursive:true,force:true})); initialize(root,packageRoot,{name:'Test',language,ai:'copilot'}); return services(root); }
function source(s,id='BR-001'){return s.load().artifacts.find(a=>a.artifact.metadata.id===id);}
function edit(s,id,fn){const a=source(s,id), doc=structuredClone(a.artifact);fn(doc);s.workspace.write(a.path,stringify(doc));}
function proposal(s){const a=source(s),doc=structuredClone(a.artifact);doc.metadata.title+=' revisada';s.createChange('review','Review rule');s.stage('review',a.path,stringify(doc));return a;}
const code=c=>e=>e.code===c;
test('integrated profiles, official Gherkin parser and decision bindings pass strict checks',t=>{const s=fixture(t);assert.equal(s.validate(true).valid,true);assert.equal(s.load().artifacts.length,11);const r=s.test();assert.equal(r.tests.length,4);assert.equal(r.passed,true);assert.deepEqual(r.unboundScenarios,[]);assert.ok(graph(s.load(),'BR-001','in',2).edges.length);});
test('English init and Copilot templates are rendered with no overwrite',t=>{const s=fixture(t,'en');assert.equal(s.validate(true).valid,true);assert.ok(existsSync(join(s.workspace.root,'.github/skills/product-process/SKILL.md')));assert.throws(()=>initialize(s.workspace.root,packageRoot,{name:'Other',language:'pt',ai:'none'}));assert.equal(s.workspace.config().name,'Test');});
test('unknown schema fields and duplicate YAML keys fail closed',t=>{const s=fixture(t),a=source(s);s.workspace.write(a.path,s.workspace.read(a.path)+'typo: true\n');assert.equal(s.validate().valid,false);s.workspace.write(a.path,'kind: BusinessRule\nkind: Term\n');assert.equal(s.validate().valid,false);});
test('duplicate IDs and wrong reference types fail validation',t=>{const s=fixture(t),a=source(s);s.workspace.write('product/duplicate.yaml',s.workspace.read(a.path));assert.equal(s.validate().valid,false);s.workspace.remove('product/duplicate.yaml');edit(s,'DEC-001',a=>a.links=[{relation:'governed-by',target:'ACT-001'}]);assert.equal(s.validate().valid,false);});
test('artifact digest tolerates key order and CRLF while baseline detects byte changes',t=>{const s=fixture(t),a=source(s),baseline=s.load().baseline;const d=a.artifact;s.workspace.write(a.path,stringify({spec:d.spec,metadata:d.metadata,links:d.links,kind:d.kind,apiVersion:d.apiVersion}).replace(/\n/g,'\r\n'));assert.equal(source(s).digest,a.digest);assert.notEqual(s.load().baseline,baseline);});
test('finite decision domains detect gaps and overlaps with counterexamples',t=>{const s=fixture(t),d=structuredClone(source(s,'DEC-001').artifact.spec);assert.equal(analyzeDecision(d).checked,4);d.rules.pop();assert.ok(analyzeDecision(d).issues.some(i=>i.code==='DECISION_GAP'));d.rules.push({id:'overlap',when:{},then:'ELEGIVEL'});assert.ok(analyzeDecision(d).issues.some(i=>i.code==='DECISION_OVERLAP'));});
test('decision evaluator rejects extra and mistyped inputs',t=>{const d=source(fixture(t),'DEC-001').artifact.spec;assert.throws(()=>evaluateDecision(d,{contaAtiva:'true',saldoSuficiente:true}),code('INVALID_INPUT'));assert.throws(()=>evaluateDecision(d,{contaAtiva:true,saldoSuficiente:true,extra:1}),code('INVALID_INPUT'));});
test('failed decision expectations report failure without pretending to run Gherkin steps',t=>{const s=fixture(t);edit(s,'DEC-001',a=>a.spec.cases[0].expected='CONTA_INATIVA');assert.equal(s.test().passed,false);assert.match(s.test().scope,/not executed/);});
test('narrative SBVR rule is explicitly unsupported under strict validation',t=>{const s=fixture(t);edit(s,'BR-001',a=>delete a.spec.formulation);assert.equal(s.validate().valid,true);assert.equal(s.validate(true).valid,false);});
test('unresolved SBVR bindings and process nodes fail',t=>{const s=fixture(t);edit(s,'FACT-001',a=>a.spec.roles[0].conceptRef='TERM-999');assert.equal(s.validate().valid,false);});
test('missing process flow target is rejected',t=>{const s=fixture(t);edit(s,'PROC-001',a=>a.spec.flows[0].target='missing');assert.equal(s.validate().valid,false);});
test('Gherkin unresolved ID tags cannot silently become graph links',t=>{const s=fixture(t),f=s.workspace.productFiles().find(f=>f.path.endsWith('.feature'));s.workspace.write(f.path,f.text.replace('@requirement_REQ-001','@requirement_REQ-999'));assert.equal(s.validate().valid,false);});
test('citation tracks current, stale, refresh and tampered quoted content',t=>{const s=fixture(t);s.citeInto('BR-001','notes.md');assert.equal(s.citations().citations[0].status,'current');edit(s,'BR-001',a=>a.metadata.title+=' changed');assert.equal(s.citations().citations[0].status,'stale');s.refreshCitation('notes.md');assert.equal(s.citations().citations[0].status,'current');s.workspace.write('notes.md',s.workspace.read('notes.md').replace('changed','tampered'));assert.equal(s.citations().citations[0].status,'tampered');assert.throws(()=>s.refreshCitation('notes.md'),code('UNSAFE_REFRESH'));});
test('missing historical snapshot is unresolved after source changes',t=>{const s=fixture(t),a=source(s);s.citeInto('BR-001','notes.md');edit(s,'BR-001',d=>d.metadata.title+=' changed');s.workspace.remove('.intent/snapshots/'+a.digest.slice(7)+'.json');assert.equal(s.citations().citations[0].status,'unresolved');});
test('snapshot tampering is detected',t=>{const s=fixture(t),a=source(s);s.citeInto('BR-001','notes.md');s.workspace.write('.intent/snapshots/'+a.digest.slice(7)+'.json','{}');assert.equal(s.citations().citations[0].status,'tampered');});
test('citation markers in code fences are examples rather than claims',t=>{const s=fixture(t);s.workspace.write('example.md','```markdown\n'+s.cite('BR-001')+'```\n');assert.equal(s.citations().citations.length,0);});
test('apply requires exact approval and preserves historical citation',t=>{const s=fixture(t);s.citeInto('BR-001','notes.md');proposal(s);assert.throws(()=>s.apply('review'),code('APPROVAL_REQUIRED'));s.approve('review','Reviewer');assert.equal(s.apply('review').state,'applied');assert.equal(s.citations().citations[0].status,'stale');});
test('restaging clears approval',t=>{const s=fixture(t),a=proposal(s);s.approve('review','Reviewer');s.stage('review',a.path,s.workspace.read(a.path));assert.equal(s.readChange('review').state,'draft');assert.throws(()=>s.apply('review'),code('APPROVAL_REQUIRED'));});
test('proposal tampering invalidates approval digest',t=>{const s=fixture(t);proposal(s);s.approve('review','Reviewer');const c=s.readChange('review');c.title='tampered';s.workspace.write('.intent/changes/review.json',JSON.stringify(c));assert.throws(()=>s.apply('review'),code('APPROVAL_REQUIRED'));});
test('baseline detects external edit before approval',t=>{const s=fixture(t),a=proposal(s);s.workspace.write(a.path,s.workspace.read(a.path)+'\n');assert.throws(()=>s.approve('review','Reviewer'),code('BASELINE_CONFLICT'));});
test('recovery restores interrupted write and blocks external conflict',t=>{const s=fixture(t),a=proposal(s);const c=s.approve('review','Reviewer'),before=s.workspace.read(a.path),after=c.operations[0].content;const j={version:1,change:c,entries:[{path:a.path,before,after}]};s.workspace.write('.intent/pending.json',JSON.stringify(j));s.workspace.write(a.path,after+'\n');assert.throws(()=>s.recover(),code('RECOVERY_CONFLICT'));s.workspace.write(a.path,after);assert.equal(s.recover().recovered,'review');assert.equal(s.workspace.read(a.path),before);});
test('path traversal and symlink writes cannot escape workspace',t=>{const s=fixture(t);s.createChange('safe','Safe');assert.throws(()=>s.stage('safe','product/../../evil.yaml','bad'));symlinkSync(tmpdir(),join(s.workspace.root,'escape'));assert.throws(()=>s.workspace.write('escape/evil.md','bad'));});
test('legacy migration preserves source bytes and old digests; converted items are drafts',t=>{const root=mkdtempSync(join(tmpdir(),'intent-migrate-'));t.after(()=>rmSync(root,{recursive:true,force:true}));legacyInit(root,'Legacy');const before=loadProduct(root).items.map(i=>[i.meta.id,i.digest]);const dry=migrateLegacy(root,packageRoot,true);assert.equal(dry.dryRun,true);assert.equal(existsSync(join(root,'intent.config.yaml')),false);migrateLegacy(root,packageRoot,false);assert.deepEqual(loadProduct(root).items.map(i=>[i.meta.id,i.digest]),before);const m=services(root).validate();assert.equal(m.valid,true,JSON.stringify(m.model.diagnostics));assert.ok(m.model.artifacts.every(a=>a.artifact.metadata.status==='draft'));assert.equal(services(root).validate(true).valid,false);});
test('CLI usage errors are structured JSON with exit 2',()=>{const r=spawnSync(process.execPath,[cli,'--json','validate','--wrong'],{encoding:'utf8'});assert.equal(r.status,2);assert.equal(JSON.parse(r.stderr).error.code,'USAGE_ERROR');});
test('legacy subcommand passes through root and flags',t=>{const root=mkdtempSync(join(tmpdir(),'intent-legacy-cli-'));t.after(()=>rmSync(root,{recursive:true,force:true}));legacyInit(root,'Legacy');const r=spawnSync(process.execPath,[cli,'-C',root,'legacy','validate','--json'],{encoding:'utf8'});assert.equal(r.status,0,r.stderr);assert.doesNotThrow(()=>JSON.parse(r.stdout));});
test('candidate cases block approval and apply even when the structural model is valid',t=>{const s=fixture(t),a=source(s,'DEC-001'),d=structuredClone(a.artifact);d.spec.cases[0].expected='CONTA_INATIVA';s.createChange('bad-case','Wrong expectation');s.stage('bad-case',a.path,stringify(d));assert.equal(s.candidate('bad-case').model.diagnostics.length,0);assert.throws(()=>s.approve('bad-case','Reviewer'),code('DECISION_TEST_FAILED'));assert.equal(s.readChange('bad-case').state,'draft');});
test('generated Copilot skill metadata and relative documentation links resolve',t=>{const s=fixture(t);for(const name of ['product-discover','product-behavior','product-process','product-specify','product-review']){const path=join(s.workspace.root,'.github/skills',name,'SKILL.md');const text=readFileSync(path,'utf8');const meta=parse(text.split('---')[1]);assert.equal(meta.name,name);assert.ok(meta.description);for(const [,link] of text.matchAll(/\]\((\.\.\/[^)]+)\)/g))assert.ok(existsSync(resolve(path,'..',link)),link);}});
